name: ${project.artifactId}
version: ${project.version}-SNAPSHOT
description: Controls the Ore-Generator
authors: [ Linus122, ARVIN3108 ID ]
softdepend: [ PlaceholderAPI, BentoBox ]
main: id.universenetwork.oregen.UNOreGen
api-version: 1.16
commands:
  unoregen:
    description: Reloads the plugin
    usage: /UNOreGen